### ISSUE TITLE
i use the source and it won't went let play online 

### ISSUE THREAD

**Issue by ThatDisabledKid** [General-Infinity/FNFNet#10]
it won't let me play online

**Comment by Ralsin** [comment]
have you edited `config.json` file? its binded to localhost by default so you cant go to the web and you need to manually change both `addr` and `resourceaddr` to `net.fnf.general-infinity.tech`

**Comment by TheDisabledKid** [comment]
well thats stupid

**Comment by Ralsin** [comment]
closed?
